// react-admin/src/pages/Login.js
import React from 'react'
import { Form, Input, Button, Checkbox, message } from 'antd'
import { UserOutlined, LockOutlined } from '@ant-design/icons'
import { useHistory } from 'react-router-dom'
import axios from '../axios'

function Login() {
  const [form] = Form.useForm()
  const history = useHistory()
  // 校验通过才执行
  const onFinish = values => {
    console.log('获取form表单的数据: ', values)
    axios.postJson('/login', values).then(res => {
      console.log('登录返回了', res)
      if (res.code !== 200) return message.error(res.msg)
      console.log('注册了', res)
      localStorage.setItem('token', res.body.access_token)
      localStorage.setItem('userInfo', res.body.userInfo)
      history.push('/blogList/0')
    })
  }
  const register = () => {
    form.validateFields().then(values => {
      if (values) {
        axios.postJson('/register', values).then(res => {
          if (res.code !== 200) return message.error(res.msg)
          localStorage.setItem('token', res.body.access_token)
          localStorage.setItem('userInfo', res.body.userInfo)
          history.push('/blogList/0')
        })
      }
    })
  }

  return (
    <Form
      form={form}
      name="normal_login"
      className="login-form"
      initialValues={{ remember: true }}
      onFinish={onFinish}
    >
      <Form.Item
        name="username"
        rules={[{ required: true, message: 'Please input your Username!' }]}
      >
        <Input
          prefix={<UserOutlined className="site-form-item-icon" />}
          placeholder="Username"
        />
      </Form.Item>
      <Form.Item
        name="password"
        rules={[{ required: true, message: 'Please input your Password!' }]}
      >
        <Input
          prefix={<LockOutlined className="site-form-item-icon" />}
          type="password"
          placeholder="Password"
        />
      </Form.Item>
      <Form.Item
        name="email"
        rules={[{ required: true, message: '请输入邮箱!' }]}
      >
        <Input
          prefix={<LockOutlined className="site-form-item-icon" />}
          type="email"
          placeholder="email"
        />
      </Form.Item>
      <Form.Item>
        <Form.Item name="remember" valuePropName="checked" noStyle>
          <Checkbox>Remember me</Checkbox>
        </Form.Item>

        {/* <a className="login-form-forgot" href="">
            Forgot password
          </a> */}
      </Form.Item>

      <Form.Item>
        <Button
          style={{ marginRight: '20px' }}
          type="primary"
          htmlType="submit"
          className="login-form-button"
        >
          登录
        </Button>
        <Button type="warn" onClick={register} className="login-form-button">
          注册
        </Button>
      </Form.Item>
    </Form>
  )
}

export default Login

// admin/src/pages/login/index.vue
<template>
  <el-form
    :model="ruleForm"
    status-icon
    :rules="rules"
    ref="ruleForm"
    label-width="100px"
    class="demo-ruleForm"
  >
    <el-form-item label="姓名" prop="username">
      <el-input v-model="ruleForm.username" autocomplete="off"></el-input>
    </el-form-item>
    <el-form-item label="邮箱" prop="email">
      <el-input v-model="ruleForm.email" autocomplete="off"></el-input>
    </el-form-item>
    <el-form-item label="密码" prop="password">
      <el-input v-model="ruleForm.password"></el-input>
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="submitForm('ruleForm')">登录</el-button>
      <el-button @click="register('ruleForm')">注册</el-button>
    </el-form-item>
  </el-form>
</template>
<script>
export default {
  data() {
    return {
      ruleForm: {
        username: "",
        email: "",
        password: ""
      },
      rules: {
        username: [{ required: true, message: "请输入姓名", trigger: "blur" }],
        email: [{ required: true, message: "请输入邮箱", trigger: "blur" }],
        password: [{ required: true, message: "请输入密码", trigger: "blur" }]
      }
    };
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate(valid => {
        if (valid) {
          this.axios.postJson("/login", this.ruleForm).then(res => {
            console.log("登录参数", res);
            if (res.code != 200)
              return this.$message({
                type: "warning",
                message: `${res.msg}`
              });

            let data = res.body;
            localStorage.setItem("token", data.access_token);
            localStorage.setItem("userInfo", data.userInfo);
            this.$router.push("/ArticleList");
          });
        } else {
          return false;
        }
      });
    },
    register(formName) {
      this.$refs[formName].validate(valid => {
        if (valid) {
          this.axios.postJson("/register", this.ruleForm).then(res => {
            if (res.code != 200)
              return this.$message({
                type: "warning",
                message: `${res.msg}`
              });
            let data = res.body;
            localStorage.setItem("token", data.access_token);
            localStorage.setItem("userInfo", data.userInfo);
            this.$message({
              type: "success",
              message: `${res.msg}`
            });
            this.$router.push("/ArticleList");
          });
        } else {
          return false;
        }
      });
    },
    resetForm(formName) {
      this.$refs[formName].resetFields();
    }
  }
};
</script>
